version: '3'

services:
  fyip:
    image: fyip:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fyip
    ports:
      - "5000:5000"
    environment:
      - TZ=Asia/Shanghai
      - TENCENT_MAP_KEY=${TENCENT_MAP_KEY:-LQOBZ-LCOWV-T3JPC-UQLNL-FQL7J-KEB3V}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS:-*}
      - ALLOWED_IPS=${ALLOWED_IPS:-127.0.0.1,172.17.0.1,localhost}
      - DAILY_LIMIT=${DAILY_LIMIT:-5}
      - FLASK_ENV=production
      - FLASK_APP=app.main
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - fyip_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/current"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  fyip_net:
    driver: bridge